/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestContract } from "./TestContract";
export type { VDAVerificationContract } from "./VDAVerificationContract";
