/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestContract__factory } from "./TestContract__factory";
export { VDAVerificationContract__factory } from "./VDAVerificationContract__factory";
